# Generated by Django 4.1 on 2022-08-19 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='number_of_pages',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='publish_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
